steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest || exit 0']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '--tag', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest',
            '.'
        ]
images: ['gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest']
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _SERVICE_NAME: eurostat-scraper
