steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/data-for-good-concepts/eurostat-scraper', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/data-for-good-concepts/eurostat-scraper']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'eurostat-scraper', '--image', 'gcr.io/data-for-good-concepts/eurostat-scraper', '--region', 'europe-west1']
images:
- gcr.io/data-for-good-concepts/eurostat-scraper
