name: deploy-cloudrun
on: push

env:
  SERVICE: 'eurostat-scraper'
  PROJECT_ID: 'data-for-good-concepts'
  REGION: 'europe-west1'

jobs:
  deploy-scraping-service:
    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Checkout 🛎'
      uses: 'actions/checkout@main'

    - name: 'Authenticate GCP 🔐'
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GC_SA_ADMNIN_KEY }}'

    - name: 'Set up Cloud SDK 🌥'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Build image 💿'
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE"

    - name: 'Deploy service 🏗'
      id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: '${{ env.SERVICE }}'
        image: 'gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest'
        region: '${{ env.REGION }}'

    - name: 'Make service public 🌎'
      run: |
        gcloud run services set-iam-policy ${{ env.SERVICE }} policy.yaml

