name: deploy-cloudrun
on:
  push:
    branches:
      - 'main'

env:
  SERVICE: 'serverless-scraping-service'
  PROJECT_ID: 'data-for-good-concepts'
  REGION: 'europe-west1'

jobs:
  deploy-scraping-service:
    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Checkout 🛎'
      uses: 'actions/checkout@main'

    - name: 'Authenticate GCP 🔐'
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GC_SA_ADMNIN_KEY }}'

    - name: 'Set up Cloud SDK 🌥'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Build image 💿'
      run: |-
        gcloud builds submit \
          --region='${{ env.REGION }}'
